import os

# Create a PyMOL session from the pdb file generated by AlphaFold
def protein_painter(pdb_input, output, pymol_binary):
    # File path for the PyMol session
    session_path = f"{output}/pLDDT.pse"

    color_plddt = (
        " color 0x024fcc, b < 100; color 0x60c2e8, b < 90; color 0xf37842, b < 70;  color 0xf9d613, b < 50"
    )

    # Terminal Command to open pdb file, color protein by pLDDT (b-factor) and save the session in the output directory
    pymol_command = f'{pymol_binary} -cq {str(pdb_input)} -d "{color_plddt}; save {session_path}"'

    # Run terminal command
    os.system(pymol_command)

    if os.path.isfile(session_path):
        print("\npLDDT data visualised.")

    else:
        print("\nERROR: visualisation failed.")
